/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 27 16:56:49 GMT 2019
 */

package com.saumitra.sessionmgmt.service;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saumitra.sessionmgmt.service.SessionService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SessionService_ESTest extends SessionService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SessionService sessionService0 = new SessionService();
      int int0 = sessionService0.sum(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SessionService sessionService0 = new SessionService();
      int int0 = sessionService0.sum(0, 932);
      assertEquals(932, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SessionService sessionService0 = new SessionService();
      int int0 = sessionService0.sum((-2316), (-2316));
      assertEquals((-4632), int0);
  }
}
